# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1YNEzbcuRVQMa9oenA3IAEt3Xhvv9yJ0w
"""

# 📦 Import required libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')  # Ignore warnings for cleaner output

# 📥 Load the dataset
df = pd.read_csv('/content/insurance (1).csv')
df

# 📋 Check dataset structure
df.info()  # Data types and missing values
df.describe()  # Statistical summary of numerical features

# 📊 BMI Distribution with KDE (Kernel Density Estimation)
plt.figure(figsize=(12, 5))
sns.histplot(df['bmi'], kde=True)
plt.title("BMI Distribution with KDE")
plt.xlabel("BMI")
plt.ylabel("Frequency")
plt.show()

# 📦 Box plot to detect outliers in BMI
plt.figure(figsize=(10, 4))
sns.boxplot(x=df['bmi'])
plt.title("Box plot of BMI")
plt.show()

# 🧹 Outlier removal using IQR method
Q1 = df['bmi'].quantile(0.25)
Q3 = df['bmi'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(f"Lower Bound: {lower_bound} , Upper Bound: {upper_bound}")

# 🚫 Remove duplicate rows if any
df.drop_duplicates(inplace=True)

# ✅ Filter out outliers
df_cleaned = df[(df['bmi'] >= lower_bound) & (df['bmi'] <= upper_bound)]
df_cleaned

# 🔁 Re-plot BMI after removing outliers
plt.figure(figsize=(12, 5))
sns.histplot(df_cleaned['bmi'], kde=True)
plt.title("BMI Distribution after Removing Outliers")
plt.xlabel("BMI")
plt.ylabel("Frequency")
plt.show()

# 🔁 Re-plot Box plot
plt.figure(figsize=(10, 4))
sns.boxplot(x=df_cleaned['bmi'])
plt.title("Box plot of BMI (Cleaned Data)")
plt.show()

# 🧠 One-hot encoding for categorical variables (e.g., sex, smoker, region)
df_cleaned = pd.get_dummies(df_cleaned, drop_first=True)
df_cleaned

# 🔍 Correlation matrix
plt.figure(figsize=(16, 10))  # Increase heatmap size
sns.heatmap(df_cleaned.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# 🛠️ Feature Selection
# Using only 'age', 'bmi' and 'smoker_yes' as features
x = df_cleaned[['age', 'bmi', 'smoker_yes']]
y = df_cleaned['charges']

# 🔀 Split the dataset into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=23)

# 📈 Train Linear Regression Model
model = LinearRegression()
model.fit(x_train, y_train)

# 📊 Make predictions
y_pred = model.predict(x_test)
y_train_pred = model.predict(x_train)

# ✅ Evaluate the model
print(f'R² Score (Testing): {r2_score(y_test, y_pred)}')
print(f'R² Score (Training): {r2_score(y_train, y_train_pred)}')
print(f'Mean Squared Error (Testing): {mean_squared_error(y_test, y_pred)}')
print(f'Mean Squared Error (Training): {mean_squared_error(y_train, y_train_pred)}')

# 🔍 Predict charges for a new input: [age=25, bmi=20, smoker=No (0)]
model.predict([[25, 20, 0]])

# 💾 Save the trained model using pickle
import pickle
with open('Linear_Regression.pkl', 'wb') as file:
    pickle.dump(model, file)
