# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNEzbcuRVQMa9oenA3IAEt3Xhvv9yJ0w
"""

import pandas as pd

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.linear_model import LinearRegression

import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/insurance (1).csv')
df

df.info()

df.describe() # Statistical Summery 📈📊

plt.figure(figsize = (12,5))


sns.histplot(df['bmi'], kde = True)
plt.title("BMI Distribution with KDE")
plt.xlabel("BMI")
plt.ylabel("Frequency")
plt.show()



plt.figure(figsize = (10,4))
sns.boxplot(x = df['bmi'])
plt.title("Box plot of BMI")
plt.show()

#remove the outliers

Q1 = df['bmi'].quantile(0.25)
Q3 = df['bmi'].quantile(0.75)


IQR = Q3 - Q1

lower_bound = Q1 - 1.5*IQR
upper_bound = Q3 + 1.5*IQR

print(f" lower : {lower_bound} , upper : {upper_bound}")

df.drop_duplicates(inplace = True)

df_cleaned =  df[(df['bmi'] >= lower_bound ) & (df['bmi'] <= upper_bound)]

df_cleaned

plt.figure(figsize = (12,5))


sns.histplot(df_cleaned['bmi'], kde = True)
plt.title("BMI Distribution with KDE")
plt.xlabel("BMI")
plt.ylabel("Frequency")
plt.show()



plt.figure(figsize = (10,4))
sns.boxplot(x = df_cleaned['bmi'])
plt.title("Box plot of BMI")
plt.show()

df_cleaned

# One Hot encoding
df_cleaned = pd.get_dummies(df_cleaned,drop_first = True)
df_cleaned

df_cleaned.corr()

# Set the figure size (width, height in inches)
plt.figure(figsize=(16, 10))  # You can adjust the values as needed

# Create the heatmap
sns.heatmap(df_cleaned.corr(), annot=True, cmap='coolwarm', fmt=".2f")

# Display the plot
plt.show()

df_cleaned.columns

# Feature engineering 😎
x = df_cleaned[['age', 'bmi','smoker_yes']]
y = df_cleaned['charges']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=23)

#train the model

model = LinearRegression()

model.fit(x_train,y_train)

y_pred =  model.predict(x_test)
y_train_pred = model.predict(x_train)

print(f' Testing results : {r2_score(y_test,y_pred)}')
print(f' Training results : {r2_score(y_train,y_train_pred)}')

print(f' Testing results : {mean_squared_error(y_test,y_pred)}')
print(f' Training results : {mean_squared_error(y_train,y_train_pred)}')

model.predict([[25,20,0]])

import pickle
with open('Linear_Regression.pkl','wb') as file:
  pickle.dump(model,file)

